#!/usr/bin/env bun
/**
 * journey.ts — validate and render a journey spine.
 *
 *   bun journey.ts validate docs/journeys/app.yaml
 *   bun journey.ts render   docs/journeys/app.yaml --out docs/journeys/app.md
 *
 * The spine is the source of truth. The markdown is generated; never hand-edit it.
 */

type Actor = { id: string; name: string; type?: string };
type Screen = { id: string; route?: string; bands?: string[]; states?: string[] };
type Step = {
  id: string;
  title: string;
  screen?: string;
  state?: string;
  sees?: string;
  does?: string;
  next?: string | string[];
  satisfaction?: number;
  criteria?: string[];
};
type Journey = {
  id: string;
  title: string;
  actor?: string;
  goal?: string;
  proves?: string;
  steps: Step[];
};
type Feature = { id: string; title: string; serves?: string[] };
type Spine = {
  product?: string;
  source?: string;
  actors?: Actor[];
  screens?: Screen[];
  journeys?: Journey[];
  features?: Feature[];
};

const errors: string[] = [];
const warnings: string[] = [];
const err = (m: string) => errors.push(m);
const warn = (m: string) => warnings.push(m);

const nexts = (s: Step): string[] =>
  s.next == null ? [] : Array.isArray(s.next) ? s.next : [s.next];

function validate(spine: Spine): void {
  if (!spine.product) err("top level: `product` is required");
  if (!spine.journeys?.length) {
    err("top level: at least one journey is required");
    return;
  }

  const actorIds = new Set((spine.actors ?? []).map((a) => a.id));
  const screens = new Map((spine.screens ?? []).map((s) => [s.id, s]));
  const stepIds = new Set<string>();
  const usedScreens = new Set<string>();

  for (const j of spine.journeys) {
    if (!/^J\d+$/.test(j.id)) err(`${j.id}: journey id must look like J1`);
    if (!j.steps?.length) {
      err(`${j.id}: has no steps`);
      continue;
    }
    if (j.actor && !actorIds.has(j.actor)) err(`${j.id}: unknown actor "${j.actor}"`);

    const local = new Set(j.steps.map((s) => s.id));
    const referenced = new Set<string>();

    for (const s of j.steps) {
      if (stepIds.has(s.id)) err(`${s.id}: duplicate step id`);
      stepIds.add(s.id);

      if (!s.id.startsWith(`${j.id}.`)) err(`${s.id}: step id must be prefixed with "${j.id}."`);
      if (!/^J\d+\.S\d+$/.test(s.id)) err(`${s.id}: step id must look like ${j.id}.S1`);
      if (!s.title) err(`${s.id}: missing title`);

      if (s.screen) {
        usedScreens.add(s.screen);
        const sc = screens.get(s.screen);
        if (!sc) err(`${s.id}: unknown screen "${s.screen}"`);
        else if (s.state && sc.states?.length && !sc.states.includes(s.state))
          err(
            `${s.id}: state "${s.state}" is not one of screen ${s.screen}'s states (${sc.states.join(", ")})`,
          );
      } else {
        warn(`${s.id}: no screen — journey steps should land somewhere`);
      }

      for (const n of nexts(s)) {
        if (n === s.id) err(`${s.id}: next points at itself`);
        else if (!local.has(n)) err(`${s.id}: next "${n}" is not a step of ${j.id}`);
        referenced.add(n);
      }

      if (s.satisfaction != null && (s.satisfaction < 1 || s.satisfaction > 5))
        err(`${s.id}: satisfaction must be 1-5`);

      for (const c of s.criteria ?? []) {
        if (!c.includes("SHALL"))
          warn(
            `${s.id}: criterion is not EARS ("WHEN <trigger> THE SYSTEM SHALL <behavior>"): ${c.slice(0, 60)}`,
          );
      }
      if (!s.criteria?.length) warn(`${s.id}: no acceptance criteria`);
    }

    const first = j.steps[0]?.id;
    for (const s of j.steps)
      if (s.id !== first && !referenced.has(s.id))
        err(`${s.id}: unreachable — no step points at it`);
    if (!j.steps.some((s) => nexts(s).length === 0))
      err(`${j.id}: no terminal step — every step has a next`);
  }

  for (const f of spine.features ?? []) {
    if (!/^F\d+$/.test(f.id)) err(`${f.id}: feature id must look like F1`);
    if (!f.serves?.length) warn(`${f.id}: serves no journey step`);
    for (const ref of f.serves ?? [])
      if (!stepIds.has(ref)) err(`${f.id}: serves unknown step "${ref}"`);
  }

  for (const sc of spine.screens ?? [])
    if (!usedScreens.has(sc.id)) warn(`screen ${sc.id}: never used by any journey step`);
}

const esc = (t: string) => t.replace(/"/g, "'").replace(/\|/g, "\\|");
const cell = (t?: string) => (t ? esc(t) : "—");

function render(spine: Spine): string {
  const out: string[] = [];
  const actors = new Map((spine.actors ?? []).map((a) => [a.id, a]));

  out.push(`# ${spine.product ?? "Product"} — journey spine`, "");
  out.push("<!-- Generated by journey.ts. Edit the .yaml spine, not this file. -->", "");
  if (spine.source) out.push(`Design doc: [${spine.source}](${spine.source})`, "");

  if (spine.actors?.length) {
    out.push("## Actors", "", "| ID | Actor | Type |", "|---|---|---|");
    for (const a of spine.actors)
      out.push(`| \`${a.id}\` | ${esc(a.name)} | ${a.type ?? "person"} |`);
    out.push("");
  }

  for (const j of spine.journeys ?? []) {
    const who = j.actor ? (actors.get(j.actor)?.name ?? j.actor) : "—";
    out.push(`## ${j.id} · ${esc(j.title)}`, "");
    out.push(`**Actor:** ${esc(who)}`);
    if (j.goal) out.push(`**Goal:** ${esc(j.goal)}`);
    if (j.proves) out.push(`**Proves:** ${esc(j.proves)}`);
    out.push("");

    out.push("```mermaid", "flowchart LR");
    for (const s of j.steps) {
      const where = s.screen ? `${s.screen}${s.state ? ` · ${s.state}` : ""}` : "";
      const label = where ? `${esc(s.title)}<br/><small>${where}</small>` : esc(s.title);
      out.push(`  ${s.id.replace(".", "_")}["${label}"]`);
    }
    for (const s of j.steps)
      for (const n of nexts(s)) out.push(`  ${s.id.replace(".", "_")} --> ${n.replace(".", "_")}`);
    out.push("```", "");

    if (j.steps.some((s) => s.satisfaction != null)) {
      out.push("```mermaid", "journey", `  title ${esc(j.title)}`, `  section ${esc(who)}`);
      for (const s of j.steps)
        if (s.satisfaction != null) out.push(`    ${esc(s.title)}: ${s.satisfaction}: ${esc(who)}`);
      out.push("```", "");
    }

    out.push("| Step | Screen · state | Sees | Does | Criteria |", "|---|---|---|---|---|");
    for (const s of j.steps) {
      const where = s.screen ? `\`${s.screen}\`${s.state ? ` · ${s.state}` : ""}` : "—";
      out.push(
        `| \`${s.id}\` ${esc(s.title)} | ${where} | ${cell(s.sees)} | ${cell(s.does)} | ${s.criteria?.length ?? 0} |`,
      );
    }
    out.push("");

    const withCriteria = j.steps.filter((s) => s.criteria?.length);
    if (withCriteria.length) {
      out.push(`### ${j.id} acceptance criteria`, "");
      for (const s of withCriteria) {
        out.push(`**\`${s.id}\`** ${esc(s.title)}`, "");
        for (const c of s.criteria ?? []) out.push(`- ${c}`);
        out.push("");
      }
    }
  }

  if (spine.screens?.length) {
    out.push(
      "## Screens",
      "",
      "| Screen | Route | Bands | States | Used by |",
      "|---|---|---|---|---|",
    );
    for (const sc of spine.screens) {
      const used = (spine.journeys ?? [])
        .flatMap((j) => j.steps)
        .filter((s) => s.screen === sc.id)
        .map((s) => `\`${s.id}\``);
      out.push(
        `| \`${sc.id}\` | ${sc.route ? `\`${sc.route}\`` : "—"} | ${sc.bands?.join(", ") ?? "—"} | ${sc.states?.join(", ") ?? "—"} | ${used.join(" ") || "—"} |`,
      );
    }
    out.push("");
  }

  if (spine.features?.length) {
    out.push("## Features", "", "| Feature | Serves | Journeys |", "|---|---|---|");
    for (const f of spine.features) {
      const js = [...new Set((f.serves ?? []).map((r) => r.split(".")[0]))].join(", ");
      out.push(
        `| \`${f.id}\` ${esc(f.title)} | ${(f.serves ?? []).map((r) => `\`${r}\``).join(" ") || "—"} | ${js || "—"} |`,
      );
    }
    out.push("");

    const served = new Set((spine.features ?? []).flatMap((f) => f.serves ?? []));
    const orphans = (spine.journeys ?? []).flatMap((j) => j.steps).filter((s) => !served.has(s.id));
    if (orphans.length) {
      out.push(
        `**Steps no feature serves yet:** ${orphans.map((s) => `\`${s.id}\``).join(" ")}`,
        "",
      );
    }
  }

  return out.join("\n");
}

const [cmd, file, ...rest] = process.argv.slice(2);
if (!cmd || !file || !["validate", "render"].includes(cmd)) {
  console.error("usage: bun journey.ts <validate|render> <spine.yaml> [--out <file.md>]");
  process.exit(2);
}

let spine: Spine;
try {
  spine = Bun.YAML.parse(await Bun.file(file).text()) as Spine;
} catch (e) {
  console.error(`could not parse ${file}: ${(e as Error).message}`);
  process.exit(1);
}

validate(spine);
for (const w of warnings) console.error(`warn  ${w}`);
for (const e of errors) console.error(`ERROR ${e}`);

if (errors.length) {
  console.error(`\n${errors.length} error(s), ${warnings.length} warning(s) — spine is not valid.`);
  process.exit(1);
}

if (cmd === "validate") {
  console.error(`ok: ${file} is valid (${warnings.length} warning(s)).`);
  process.exit(0);
}

const md = render(spine);
const outIdx = rest.indexOf("--out");
const outPath = outIdx === -1 ? undefined : rest[outIdx + 1];
if (outPath) {
  await Bun.write(outPath, `${md}\n`);
  console.error(`wrote ${outPath}`);
} else {
  console.log(md);
}
